name: chemvae
channels:
  - rdkit
  - conda-forge

dependencies:
  - keras=2.0.6
  - tensorflow=2.5.0
  - h5py
  - hdf5
  - pandas
  - python=3.8.5
  - scikit-learn
  - boost
  - rdkit
  - yaml
  - numpy
  - matplotlib
